<?php

use App\Models\Contact;
use App\Models\Exercise;
use App\Models\TrainingAccess;
use App\Models\TrainingProfile;
use App\Models\TrainingRestriction;
use App\Models\WorkoutSession;
use App\Training\Engine\TrainingEngine;
use App\Training\Enums\BodyRegion;
use App\Training\Enums\ExperienceLevel;
use App\Training\Enums\RestrictionStatus;
use App\Training\Enums\SplitType;
use App\Training\Enums\TrainingGoal;
use App\Training\Enums\TrainingLocation;
use App\Training\Enums\WorkoutSessionStatus;
use App\Training\Support\BodyRegionCanonicalMapper;
use App\Training\Support\ProgressionEvaluator;
use App\Training\Support\SafetyRestrictionResolver;
use App\Training\Support\TrainingAccessGate;
use App\Training\Support\TrainingHistoryContextProvider;

// Nombres deliberadamente distintos a los helpers de TrainingEngineTest.php
// (makeReadyContact/trainingEngine) para evitar colisión de funciones
// globales entre archivos de test que Pest carga en el mismo proceso.

function readyContactForSnapshot(array $profileOverrides = []): Contact
{
    $contact = Contact::factory()->create();

    TrainingProfile::factory()->create(array_merge([
        'contact_id' => $contact->id,
        'split_type' => SplitType::FullBody,
    ], $profileOverrides));

    TrainingAccess::factory()->create(['contact_id' => $contact->id]);

    return $contact->fresh();
}

function snapshotEngine(): TrainingEngine
{
    $safetyResolver = new SafetyRestrictionResolver(new BodyRegionCanonicalMapper);

    return new TrainingEngine(
        new TrainingAccessGate,
        $safetyResolver,
        new TrainingHistoryContextProvider($safetyResolver),
        new ProgressionEvaluator,
    );
}

// ── A: una nueva WorkoutSession obtiene exactamente un snapshot ──

it('A: a new WorkoutSession generated by decideNextSession() gets exactly one prescription_context_snapshot', function () {
    $contact = readyContactForSnapshot();
    Exercise::factory()->create(['muscle_group' => 'chest']);

    $session = snapshotEngine()->decideNextSession($contact);

    expect($session->prescription_context_snapshot)->not->toBeNull();
    expect($session->prescription_context_snapshot)->toBeArray();
    expect($session->prescription_context_snapshot['schema_version'])->toBe(1);
});

// ── B: contiene los valores reales usados por el motor ──

it('B: the snapshot contains the real profile values used by the engine at that time', function () {
    $contact = readyContactForSnapshot([
        'goal' => TrainingGoal::BuildMuscle,
        'experience_level' => ExperienceLevel::Intermediate,
        'primary_focus' => ['chest'],
        'secondary_focus' => ['back'],
        'training_location' => TrainingLocation::Gym,
        'available_equipment' => ['dumbbell'],
        'equipment_fully_equipped' => false,
        'split_type' => SplitType::FullBody,
    ]);
    Exercise::factory()->create(['muscle_group' => 'chest']);

    $session = snapshotEngine()->decideNextSession($contact);
    $snapshot = $session->prescription_context_snapshot;

    expect($snapshot['goal'])->toBe('build_muscle');
    expect($snapshot['experience_level'])->toBe('intermediate');
    expect($snapshot['primary_focus'])->toBe(['chest']);
    expect($snapshot['secondary_focus'])->toBe(['back']);
    expect($snapshot['training_location'])->toBe('gym');
    expect($snapshot['available_equipment'])->toBe(['dumbbell']);
    expect($snapshot['equipment_fully_equipped'])->toBeFalse();
    expect($snapshot['split_type'])->toBe('full_body');

    // Fundación Temporal (D046): generated_at representa el instante de
    // PRESCRIPCIÓN (prescribed_at conceptual) — no el de entrega por
    // WhatsApp (ese timestamp no existe todavía). Hoy coincide (al segundo
    // — scheduled_at pierde microsegundos por el cast 'datetime'/columna
    // MySQL, un detalle de precisión de la ORM, no una diferencia
    // semántica) con scheduled_at de la misma fila porque TrainingEngine no
    // soporta programación anticipada, pero son dos conceptos distintos:
    // esta aserción demuestra la coincidencia ACTUAL, no una equivalencia
    // conceptual permanente.
    expect($snapshot['generated_at'])->not->toBeNull();
    expect(\Carbon\Carbon::parse($snapshot['generated_at'])->format('Y-m-d H:i:s'))
        ->toBe($session->scheduled_at->format('Y-m-d H:i:s'));
});

// ── C: contiene las restricciones activas relevantes en el momento de prescripción ──

it('C: the snapshot active_safety_tags matches exactly what SafetyRestrictionResolver resolved for that profile', function () {
    $contact = readyContactForSnapshot(['restrictions' => ['lesión de hombro']]);
    TrainingRestriction::factory()->create([
        'contact_id' => $contact->id,
        'body_region' => BodyRegion::Knee,
        'status' => RestrictionStatus::Confirmed,
    ]);
    Exercise::factory()->create(['muscle_group' => 'chest']);

    $session = snapshotEngine()->decideNextSession($contact);

    $resolver = new SafetyRestrictionResolver(new BodyRegionCanonicalMapper);
    $expectedTags = $resolver->activeSafetyBodyRegions($contact->trainingProfile);

    expect($session->prescription_context_snapshot['active_safety_tags'])->toEqualCanonicalizing($expectedTags);
    expect($session->prescription_context_snapshot['active_safety_tags'])->toContain('shoulder', 'knee');
});

// ── D: cambiar TrainingProfile después no cambia el snapshot histórico ──

it('D: changing the TrainingProfile after generation does not change the historical snapshot', function () {
    $contact = readyContactForSnapshot(['goal' => TrainingGoal::GeneralFitness]);
    Exercise::factory()->create(['muscle_group' => 'chest']);

    $session = snapshotEngine()->decideNextSession($contact);
    $originalSnapshot = $session->prescription_context_snapshot;

    $contact->trainingProfile->update(['goal' => TrainingGoal::LoseWeight]);

    $session->refresh();

    // toEqual (no toBe): la columna JSON de MySQL no garantiza preservar el
    // orden de claves al reserializar — es un detalle de la codificación,
    // no una diferencia de valor. La inmutabilidad se demuestra por
    // igualdad de VALORES, no por identidad literal de bytes/orden.
    expect($session->prescription_context_snapshot)->toEqual($originalSnapshot);
    expect($session->prescription_context_snapshot['goal'])->toBe('general_fitness');
});

// ── E: cambiar una restricción después no cambia el snapshot histórico ──

it('E: confirming a new restriction after generation does not change the historical snapshot', function () {
    $contact = readyContactForSnapshot();
    Exercise::factory()->create(['muscle_group' => 'chest']);

    $session = snapshotEngine()->decideNextSession($contact);
    $originalTags = $session->prescription_context_snapshot['active_safety_tags'];

    TrainingRestriction::factory()->create([
        'contact_id' => $contact->id,
        'body_region' => BodyRegion::Shoulder,
        'status' => RestrictionStatus::Confirmed,
    ]);

    $session->refresh();

    expect($session->prescription_context_snapshot['active_safety_tags'])->toBe($originalTags);
    expect($session->prescription_context_snapshot['active_safety_tags'])->not->toContain('shoulder');
});

// ── F: generar otra sesión después de cambiar el perfil produce otro snapshot con el nuevo contexto ──

it('F: generating a new session after changing the profile produces a different snapshot reflecting the new context', function () {
    $contact = readyContactForSnapshot(['goal' => TrainingGoal::GeneralFitness]);
    Exercise::factory()->create(['muscle_group' => 'chest']);

    $firstSession = snapshotEngine()->decideNextSession($contact);
    $firstSnapshot = $firstSession->prescription_context_snapshot;

    $firstSession->update(['status' => WorkoutSessionStatus::Completed, 'completed_at' => now()]);
    $contact->trainingProfile->update(['goal' => TrainingGoal::Endurance]);

    $secondSession = snapshotEngine()->decideNextSession($contact->fresh());
    $secondSnapshot = $secondSession->prescription_context_snapshot;

    expect($secondSession->id)->not->toBe($firstSession->id);
    expect($firstSnapshot['goal'])->toBe('general_fitness');
    expect($secondSnapshot['goal'])->toBe('endurance');
});

// ── G: el snapshot no se recalcula al consultar la sesión ──

it('G: reading the same session twice returns an identical snapshot — never recomputed', function () {
    $contact = readyContactForSnapshot();
    Exercise::factory()->create(['muscle_group' => 'chest']);

    $session = snapshotEngine()->decideNextSession($contact);
    $sessionId = $session->id;

    $firstRead = WorkoutSession::find($sessionId)->prescription_context_snapshot;
    $secondRead = WorkoutSession::find($sessionId)->prescription_context_snapshot;

    expect($firstRead)->toBe($secondRead);
});

// ── H: sesiones históricas existentes sin snapshot no se inventan ──

it('H: a WorkoutSession created directly (bypassing TrainingEngine) has a null snapshot, never fabricated', function () {
    $contact = Contact::factory()->create();

    $session = WorkoutSession::factory()->create(['contact_id' => $contact->id]);

    expect($session->prescription_context_snapshot)->toBeNull();
});

// ── I: no hay regresión en la creación de sesiones ──

it('I: generating a session still produces the expected WorkoutExercises, unaffected by the snapshot addition', function () {
    $contact = readyContactForSnapshot(['goal' => TrainingGoal::GeneralFitness]);
    Exercise::factory()->create(['muscle_group' => 'chest', 'name' => 'Press de banca']);

    $session = snapshotEngine()->decideNextSession($contact);

    expect($session->status)->toBe(WorkoutSessionStatus::Scheduled);
    expect($session->generated_by)->toBe('training_engine');
    expect($session->workoutExercises)->toHaveCount(1);
});

// ── J: decided_focus representa el foco usado en la prescripción, no el next_focus posterior ──

it('J: decided_focus captures the focus actually used for prescription — distinct from the next_focus written afterwards', function () {
    $contact = readyContactForSnapshot(['split_type' => SplitType::UpperLower]);
    Exercise::factory()->create(['muscle_group' => 'chest']);

    $session = snapshotEngine()->decideNextSession($contact);
    $decidedFocus = $session->prescription_context_snapshot['decided_focus'];

    $profileAfter = $contact->trainingProfile()->first()->fresh();

    expect($decidedFocus)->not->toBeNull();
    expect($profileAfter->next_focus)->not->toBeNull();
    expect($decidedFocus)->not->toBe($profileAfter->next_focus);
});
